# Generated by Django 4.2.4 on 2023-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='expirence',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
